// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32eJT1QsYOIqrP8PgwivTs4o6nFcs2Go',
    appId: '1:262036457410:web:770aac039abc3a79d8b85b',
    messagingSenderId: '262036457410',
    projectId: 'taskflow-mobile-a41d8',
    authDomain: 'taskflow-mobile-a41d8.firebaseapp.com',
    storageBucket: 'taskflow-mobile-a41d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZnzmKIHjDk3jCfYek1_8A5HycvVJqQQ',
    appId: '1:262036457410:android:d3ad77d1644d14fcd8b85b',
    messagingSenderId: '262036457410',
    projectId: 'taskflow-mobile-a41d8',
    storageBucket: 'taskflow-mobile-a41d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_8lhqhgpmKOnU4x73HeyFvysJWI8HFnI',
    appId: '1:262036457410:ios:6222b9ddb5de93e4d8b85b',
    messagingSenderId: '262036457410',
    projectId: 'taskflow-mobile-a41d8',
    storageBucket: 'taskflow-mobile-a41d8.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlocCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_8lhqhgpmKOnU4x73HeyFvysJWI8HFnI',
    appId: '1:262036457410:ios:6222b9ddb5de93e4d8b85b',
    messagingSenderId: '262036457410',
    projectId: 'taskflow-mobile-a41d8',
    storageBucket: 'taskflow-mobile-a41d8.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlocCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC32eJT1QsYOIqrP8PgwivTs4o6nFcs2Go',
    appId: '1:262036457410:web:8088f506bf42734dd8b85b',
    messagingSenderId: '262036457410',
    projectId: 'taskflow-mobile-a41d8',
    authDomain: 'taskflow-mobile-a41d8.firebaseapp.com',
    storageBucket: 'taskflow-mobile-a41d8.firebasestorage.app',
  );
}
